# В этом файле содержатся комментарии, которые помогут вам начать работу.
# Если вам нужна дополнительная помощь, обратитесь к справочному руководству Docker compose по адресу
# https://docs.docker.com/compose/compose-file/

# Здесь инструкции определяют ваше приложение как две службы, называемые "todo-app" и “todo-database”.
# Сервис “todo-app” создан на основе файла Docker в каталоге /app,
#, а сервис “todo-database” использует официальный образ MongoDB 
# из Docker Hub - https://hub.docker.com/_/mongo. 
# Здесь вы можете добавить другие сервисы, от которых может зависеть ваше приложение.

services:
  todo-app:
    build:
      context: ./app
    depends_on:
      - todo-database
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 35729:35729
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app
          target: /usr/src/app
          action: sync

  todo-database:
    image: mongo:6
    volumes: 
      - multi-container-app_data:/data/db
    ports:
      - 27017:27017

volumes:
  multi-container-app_data: